version: '3.1'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "entain"
    ports:
      - "5452:5432"
    volumes:
      - ./internal/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appdb

  app:
    image: golang:1.19
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "8888:8888"
    networks:
      - appdb


networks:
  appdb:
    driver: bridge
