basePath: /
definitions:
  handler.processRequest:
    properties:
      amount:
        type: number
      state:
        type: string
      transaction_id:
        type: string
    type: object
  model.APIError:
    properties:
      err:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact:
    email: anar.rzayev94@gmail.com
    name: Anar
  description: Entain handle user requests and process them
  title: Entain Request Process Service
  version: 0.2.13
paths:
  /api/process:
    post:
      parameters:
      - description: body
        in: body
        name: requestData
        required: true
        schema:
          $ref: '#/definitions/handler.processRequest'
      - description: Source-Type enums
        enum:
        - game
        - server
        - payment
        - invalid-header
        in: header
        name: Source-Type
        required: true
        type: string
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIError'
      summary: Process new incoming requests
      tags:
      - '[request]'
schemes:
- http
swagger: "2.0"
